config/routes.rb
Rails.application.routes.draw do
  resources :rents
  resources :properties
  resources :users

  root 'users#index'
  get 'notrented', to: 'properties#notrented'

end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
  has_one :rent
  
  validates :property_name, :address, :city, :state, :zip, :type_of_property, :sqft, :no_of_rooms, :no_of_bathrooms, presence: true
  validates :zip, length: { is: 6 }
 end

app/models/rent.rb
class Rent < ActiveRecord::Base
  belongs_to :property
  
  #validates :rent_time_period_in_months, length: { in: 11..121 }
  validates :renter_name, :rent_time_period_in_months, :rent_cost_in_dollars, :deposit_amount, presence: true
  #validates :rent_time_period_in_months, inclusion: { in: %w(11..121), message: ": %{value} is not a valid input, its range is 12 to 120" }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :properties
  
  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  def notrented
    @property = Property.all
  end
  
  
  
  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:user_id, :property_name, :address, :city, :state, :zip, :type_of_property, :sqft, :no_of_rooms, :no_of_bathrooms, :occupied_by_renter)
    end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rent, only: [:show, :edit, :update, :destroy]

  # GET /rents
  # GET /rents.json
  def index
    @rents = Rent.all
  end

  # GET /rents/1
  # GET /rents/1.json
  def show
  end

  # GET /rents/new
  def new
    @rent = Rent.new
  end

  # GET /rents/1/edit
  def edit
  end

  # POST /rents
  # POST /rents.json
  def create
    @rent = Rent.new(rent_params)

    respond_to do |format|
      if @rent.save
        format.html { redirect_to @rent, notice: 'Rent was successfully created.' }
        format.json { render :show, status: :created, location: @rent }
      else
        format.html { render :new }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rents/1
  # PATCH/PUT /rents/1.json
  def update
    respond_to do |format|
      if @rent.update(rent_params)
        format.html { redirect_to @rent, notice: 'Rent was successfully updated.' }
        format.json { render :show, status: :ok, location: @rent }
      else
        format.html { render :edit }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rents/1
  # DELETE /rents/1.json
  def destroy
    @rent.destroy
    respond_to do |format|
      format.html { redirect_to rents_url, notice: 'Rent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rent
      @rent = Rent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rent_params
      params.require(:rent).permit(:property_id, :renter_name, :rent_time_period_in_months, :rent_cost_in_dollars, :deposit_amount)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :notes, :no_of_properties)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Propertymgmt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :property_name %><br>
    <%= f.text_field :property_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :type_of_property %><br>
    <%= f.text_area :type_of_property %>
  </div>
  <div class="field">
    <%= f.label :sqft %><br>
    <%= f.number_field :sqft %>
  </div>
  <div class="field">
    <%= f.label :no_of_rooms %><br>
    <%= f.number_field :no_of_rooms %>
  </div>
  <div class="field">
    <%= f.label :no_of_bathrooms %><br>
    <%= f.number_field :no_of_bathrooms %>
  </div>
  <div class="field">
    <%= f.label :occupied_by_renter %><br>
    <%= f.check_box :occupied_by_renter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Properties</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Property name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Type of property</th>
      <th>Sqft</th>
      <th>No of rooms</th>
      <th>No of bathrooms</th>
      <th>Occupied by renter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.user.name %></td>
        <td><%= property.property_name %></td>
        <td><%= property.address %></td>
        <td><%= property.city %></td>
        <td><%= property.state %></td>
        <td><%= property.zip %></td>
        <td><%= property.type_of_property %></td>
        <td><%= property.sqft %></td>
        <td><%= property.no_of_rooms %></td>
        <td><%= property.no_of_bathrooms %></td>
        <td><%= property.occupied_by_renter %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><% link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/notrented.html.erb
<p id="notice"><%= notice %></p>

<h1>These are the Properties that are not occupied by any renter at this moment!</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Property name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Type of property</th>
      <th>Sqft</th>
      <th>No of rooms</th>
      <th>No of bathrooms</th>
      <th>Occupied by renter</th>
    </tr>
  </thead>

  <tbody>
    <% @property.where(:occupied_by_renter => false).each do |property| %>
      <tr>
        <td><%= property.user.name %></td>
        <td><%= property.property_name %></td>
        <td><%= property.address %></td>
        <td><%= property.city %></td>
        <td><%= property.state %></td>
        <td><%= property.zip %></td>
        <td><%= property.type_of_property %></td>
        <td><%= property.sqft %></td>
        <td><%= property.no_of_rooms %></td>
        <td><%= property.no_of_bathrooms %></td>
        <td><%= property.occupied_by_renter %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @property.user %>
</p>

<p>
  <strong>Property name:</strong>
  <%= @property.property_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @property.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @property.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @property.zip %>
</p>

<p>
  <strong>Type of property:</strong>
  <%= @property.type_of_property %>
</p>

<p>
  <strong>Sqft:</strong>
  <%= @property.sqft %>
</p>

<p>
  <strong>No of rooms:</strong>
  <%= @property.no_of_rooms %>
</p>

<p>
  <strong>No of bathrooms:</strong>
  <%= @property.no_of_bathrooms %>
</p>

<p>
  <strong>Occupied by renter:</strong>
  <%= @property.occupied_by_renter %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/rents/_form.html.erb
<%= form_for(@rent) do |f| %>
  <% if @rent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rent.errors.count, "error") %> prohibited this rent from being saved:</h2>

      <ul>
      <% @rent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :property_id %><br>
    <%= f.text_field :property_id %>
  </div>
  <div class="field">
    <%= f.label :renter_name %><br>
    <%= f.text_field :renter_name %>
  </div>
  <div class="field">
    <%= f.label :rent_time_period_in_months %><br>
    <%= f.number_field :rent_time_period_in_months %>
  </div>
  <div class="field">
    <%= f.label :rent_cost_in_dollars %><br>
    <%= f.number_field :rent_cost_in_dollars %>
  </div>
  <div class="field">
    <%= f.label :deposit_amount %><br>
    <%= f.number_field :deposit_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rents/edit.html.erb
<h1>Editing Rent</h1>

<%= render 'form' %>

<%= link_to 'Show', @rent %> |
<%= link_to 'Back', rents_path %>

app/views/rents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rents</h1>

<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>Renter name</th>
      <th>Rent time period in months</th>
      <th>Rent cost in dollars</th>
      <th>Deposit amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= rent.property.property_name %></td>
        <td><%= rent.renter_name %></td>
        <td><%= rent.rent_time_period_in_months %></td>
        <td><%= rent.rent_cost_in_dollars %></td>
        <td><%= rent.deposit_amount %></td>
        <td><%= link_to 'Show', rent %></td>
        <td><%= link_to 'Edit', edit_rent_path(rent) %></td>
        <td><%= link_to 'Destroy', rent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
If you want to rent a property, first please view the properties page and know the id of the property you want to rent, so that you can enter its value in the first entry of the new rent link below this.
<%= link_to 'New Rent', new_rent_path %>

app/views/rents/new.html.erb
<h1>New Rent</h1>

<%= render 'form' %>

<%= link_to 'Back', rents_path %>

app/views/rents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @rent.property %>
</p>

<p>
  <strong>Renter name:</strong>
  <%= @rent.renter_name %>
</p>

<p>
  <strong>Rent time period in months:</strong>
  <%= @rent.rent_time_period_in_months %>
</p>

<p>
  <strong>Rent cost in dollars:</strong>
  <%= @rent.rent_cost_in_dollars %>
</p>

<p>
  <strong>Deposit amount:</strong>
  <%= @rent.deposit_amount %>
</p>

<%= link_to 'Edit', edit_rent_path(@rent) %> |
<%= link_to 'Back', rents_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :no_of_properties %><br>
    <%= f.number_field :no_of_properties %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>


If you want to view the properties of a user please click the "Show my properties list" button side of that user
<br>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Notes</th>
      <th>No of properties</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.notes %></td>
        <td><%= user.no_of_properties %></td>
        <td><%= link_to 'Show my properties list', user %></td>
        <td><%= link_to 'Edit my properties list', edit_user_path(user) %></td>
        <td><%link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<br>
<br>
If you want to see the properties that are not rented or not occupied by any renter at this time, now click this link 
<%= link_to 'notrented', notrented_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Properties of this User only!</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Property name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Type of property</th>
      <th>Sqft</th>
      <th>No of rooms</th>
      <th>No of bathrooms</th>
      <th>Occupied by renter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.properties.each do |property| %>
      <tr>
        <td><%= property.user.name %></td>
        <td><%= property.property_name %></td>
        <td><%= property.address %></td>
        <td><%= property.city %></td>
        <td><%= property.state %></td>
        <td><%= property.zip %></td>
        <td><%= property.type_of_property %></td>
        <td><%= property.sqft %></td>
        <td><%= property.no_of_rooms %></td>
        <td><%= property.no_of_bathrooms %></td>
        <td><%= property.occupied_by_renter %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>